//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Supplier : Person
    {
        [StringLength(12, MinimumLength=7,ErrorMessage="The telephone number must have minimum 7 and maximum 12")]
        [Phone(ErrorMessage="Telephone number is not valid")]
        public string Telephone { get; set; }
    }
}
